name: MathGuard
main: com.example.mathguard.MathGuardPlugin
version: 1.1.0
api-version: '1.20'
author: Ella
softdepend: [Vault]

commands:
  mathguard:
    description: Reload config
    permission: mathguard.admin

permissions:
  mathguard.bypass:
    default: false
  mathguard.admin:
    default: op
